### ISSUE TITLE
Remove package-level Vitess flags

### ISSUE THREAD

**Issue by ryanpbrewster** [dolthub/vitess#174]
Similar to https://github.com/dolthub/vitess/issues/155, this is a show-stopper issue that crops up anytime you use `go-mysql-server` alongside with Vitess.

I do not believe the dolthub uses of Vitess require these to be flags at all. I do not believe you set them anywhere,

I am going to take a two-pronged approach here:
1. I'll set up a personal repo to demonstrate the flag namespace conflict
2. I'll open a PR against this vitess fork to replace all of the configurable flags with variables hard-coded to the default value

Please let me know if you think the above approach is unlikely to be accepted into this repo.

**Comment by ryanpbrewster** [comment]
Example repo demonstrating the flag collision issue: https://github.com/ryanpbrewster/vitess-conflict-example

In particular:
```
$ go test src/my_test.go 
/tmp/go-build3353698422/b001/my.test flag redefined: log_err_stacks
panic: /tmp/go-build3353698422/b001/my.test flag redefined: log_err_stacks

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00011c120, {0xc44218, 0x10f2e7c}, {0xb2be81, 0xe}, {0xb374b2, 0x1b})
        /home/ryanpbrewster/opt/go/src/flag/flag.go:879 +0x2f4
flag.BoolVar(...)
        /home/ryanpbrewster/opt/go/src/flag/flag.go:638
vitess.io/vitess/go/vt/vterrors.init.0()
        /home/ryanpbrewster/go/pkg/mod/vitess.io/vitess@v0.14.1/go/vt/vterrors/vterrors.go:103 +0x4e
FAIL    command-line-arguments  0.006s
FAIL
```

**Comment by ryanpbrewster** [comment]
@reltuk, you kindly shepherded the previous protobuf cleanup PR through. Can you recommend someone who could champion this PR?

**Comment by ryanpbrewster** [comment]
Confirming that as of commit `c7560b3fabf0d1fcdaf845662b921c5187eb9320` in go-mysql-server this issue is resolved, I'll leave my example repo up w/ documentation.
